import { chromium } from 'playwright';
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const base = process.env.BASE_URL || 'http://localhost:8532';
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
await page.goto(`${base}/?debug=1`);
await page.waitForFunction(() => window.__astro && window.__astro.getState().state === 'menu');
await sleep(500);
await page.screenshot({ path: 'marketing/screenshot-menu.png' });
await page.evaluate(() => { window.__astro.setUnlocked(5); window.__astro.startMission(2); });
await sleep(800);
await page.evaluate(() => window.__astro.clickWorld(5, 5));
await sleep(3500);
await page.screenshot({ path: 'marketing/screenshot-gameplay.png' });
await page.evaluate(() => {
  const gg = window.__astro.getState().guards[0];
  window.__astro.teleport(1, Math.round(gg.x), Math.round(gg.y) + 1);
  window.__astro.tryEmp();
});
await sleep(350);
await page.screenshot({ path: 'marketing/screenshot-emp.png' });
await browser.close();
console.log('marketing screenshots refreshed');
